"""empty message

Revision ID: 801eef9cb7a3
Revises: 762402052503
Create Date: 2021-03-30 02:39:36.980729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801eef9cb7a3'
down_revision = '762402052503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('td_task', sa.String(length=120), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todolist')
    # ### end Alembic commands ###
